### ISSUE TITLE
Project Review

### ISSUE THREAD

**Issue by bmizepatterson** [bmizepatterson/gitten-mabelli#1]
Some things to think about:
- Is the large text readable enough on top of the large images?
- How does it look on your phone/small screen? I tried to make it responsive.

Thanks for your feedback!

**Comment by Imayeti** [comment]
This website looks amazing Ben. And it seems to scale perfectly to my phone. The only thing I might change would be to make the text "Gitten Mabelli" on the front page just slightly emboldened or bigger.

**Comment by Kiwipup** [comment]
Hey Ben, your project looks really really good! I tested your google map integration as well as your forms, the screen sizing, everything I could think of and it all seems to be working very nicely! There were really only a couple things that I thought could change a little bit in my opinion: I think the restaurant name header on your home page might need to be bold or something along those lines to make it a little more readable. Also I was a little unsure at first where I would find the hours for the restaurant because the navigation links didn't mention it, but I did find it on the locations page. Lastly, on the locations page you mention the address twice, once in the small description and also under the mailing address header. Maybe you could do all of that in one spot??

Hope I was able to help!

**Comment by Kiwipup** [comment]
Also you may want to make some changes to the phone numbers field on the reservations page to only accept numbers!

**Comment by bmizepatterson** [comment]
Great suggestions, @Imayeti and @Kiwipup! Thanks!
